spring.application.name=nexacorp-ai-backend
# ????? Ollama
spring.ai.ollama.base-url=http://localhost:11434
# ?????? ??? ???? (LLM)
# ??? mistral, gemma2, qwen2.5 ? ?.?.
spring.ai.ollama.chat.model=llama3.2
spring.ai.ollama.chat.options.temperature=0.7
spring.ai.ollama.chat.options.num-ctx=4096
# ?????? ??? ??????????? (??? RAG ???????????!)
# ?????????????????? embedding-??????
spring.ai.ollama.embedding.model=nomic-embed-text
#spring.ai.ollama.embedding.model.options.num-ctx=2048